*---------------------------------------------------------------------*
*    view related data declarations
*   generation date: 24.04.2020 at 11:25:05
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZV_FMACTYP......................................*
TABLES: ZV_FMACTYP, *ZV_FMACTYP. "view work areas
CONTROLS: TCTRL_ZV_FMACTYP
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZV_FMACTYP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_FMACTYP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_FMACTYP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_FMACTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_FMACTYP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_FMACTYP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_FMACTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_FMACTYP_TOTAL.

*...processing: ZV_FMCUSAC......................................*
TABLES: ZV_FMCUSAC, *ZV_FMCUSAC. "view work areas
CONTROLS: TCTRL_ZV_FMCUSAC
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZV_FMCUSAC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_FMCUSAC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_FMCUSAC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_FMCUSAC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_FMCUSAC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_FMCUSAC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_FMCUSAC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_FMCUSAC_TOTAL.

*...processing: ZV_FMCUSGRP.....................................*
TABLES: ZV_FMCUSGRP, *ZV_FMCUSGRP. "view work areas
CONTROLS: TCTRL_ZV_FMCUSGRP
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZV_FMCUSGRP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_FMCUSGRP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_FMCUSGRP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_FMCUSGRP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_FMCUSGRP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_FMCUSGRP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_FMCUSGRP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_FMCUSGRP_TOTAL.

*...processing: ZV_TFMACPPGS....................................*
TABLES: ZV_TFMACPPGS, *ZV_TFMACPPGS. "view work areas
CONTROLS: TCTRL_ZV_TFMACPPGS
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZV_TFMACPPGS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_TFMACPPGS.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_TFMACPPGS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMACPPGS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMACPPGS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_TFMACPPGS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMACPPGS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMACPPGS_TOTAL.

*...processing: ZV_TFMACWCT.....................................*
TABLES: ZV_TFMACWCT, *ZV_TFMACWCT. "view work areas
CONTROLS: TCTRL_ZV_TFMACWCT
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZV_TFMACWCT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_TFMACWCT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_TFMACWCT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMACWCT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMACWCT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_TFMACWCT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMACWCT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMACWCT_TOTAL.

*...processing: ZV_TFMPLTYP.....................................*
TABLES: ZV_TFMPLTYP, *ZV_TFMPLTYP. "view work areas
CONTROLS: TCTRL_ZV_TFMPLTYP
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZV_TFMPLTYP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_TFMPLTYP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_TFMPLTYP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMPLTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMPLTYP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_TFMPLTYP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMPLTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMPLTYP_TOTAL.

*...processing: ZV_TFMRCTYP.....................................*
TABLES: ZV_TFMRCTYP, *ZV_TFMRCTYP. "view work areas
CONTROLS: TCTRL_ZV_TFMRCTYP
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_ZV_TFMRCTYP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZV_TFMRCTYP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZV_TFMRCTYP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMRCTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMRCTYP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZV_TFMRCTYP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZV_TFMRCTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZV_TFMRCTYP_TOTAL.

*.........table declarations:.................................*
TABLES: ZFMACPPGS                      .
TABLES: ZFMACWCT                       .
TABLES: ZTFMACTYP                      .
TABLES: ZTFMPLTYP                      .
TABLES: ZTFMRCTYP                      .
TABLES: ZTG_FMCUFLD                    .
TABLES: ZTG_FMCUGRP                    .
