*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 25.05.2020 at 01:49:36
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_EMP_ROLE..................................*
FORM GET_DATA_ZABSV_EMP_ROLE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_EMP_ROLE WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_EMP_ROLE .
ZABSV_EMP_ROLE-MANDT =
ZABS_EMP_ROLE-MANDT .
ZABSV_EMP_ROLE-PERNR =
ZABS_EMP_ROLE-PERNR .
ZABSV_EMP_ROLE-UROLE =
ZABS_EMP_ROLE-UROLE .
ZABSV_EMP_ROLE-PEVT =
ZABS_EMP_ROLE-PEVT .
ZABSV_EMP_ROLE-FPCNF =
ZABS_EMP_ROLE-FPCNF .
ZABSV_EMP_ROLE-ERNAM =
ZABS_EMP_ROLE-ERNAM .
ZABSV_EMP_ROLE-ERDAT =
ZABS_EMP_ROLE-ERDAT .
ZABSV_EMP_ROLE-ERZET =
ZABS_EMP_ROLE-ERZET .
ZABSV_EMP_ROLE-AENAM =
ZABS_EMP_ROLE-AENAM .
ZABSV_EMP_ROLE-AEDAT =
ZABS_EMP_ROLE-AEDAT .
ZABSV_EMP_ROLE-AEZET =
ZABS_EMP_ROLE-AEZET .
<VIM_TOTAL_STRUC> = ZABSV_EMP_ROLE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_EMP_ROLE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_EMP_ROLE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_EMP_ROLE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_EMP_ROLE WHERE
  PERNR = ZABSV_EMP_ROLE-PERNR .
    IF SY-SUBRC = 0.
    DELETE ZABS_EMP_ROLE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_EMP_ROLE WHERE
  PERNR = ZABSV_EMP_ROLE-PERNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_EMP_ROLE.
    ENDIF.
ZABS_EMP_ROLE-MANDT =
ZABSV_EMP_ROLE-MANDT .
ZABS_EMP_ROLE-PERNR =
ZABSV_EMP_ROLE-PERNR .
ZABS_EMP_ROLE-UROLE =
ZABSV_EMP_ROLE-UROLE .
ZABS_EMP_ROLE-PEVT =
ZABSV_EMP_ROLE-PEVT .
ZABS_EMP_ROLE-FPCNF =
ZABSV_EMP_ROLE-FPCNF .
ZABS_EMP_ROLE-ERNAM =
ZABSV_EMP_ROLE-ERNAM .
ZABS_EMP_ROLE-ERDAT =
ZABSV_EMP_ROLE-ERDAT .
ZABS_EMP_ROLE-ERZET =
ZABSV_EMP_ROLE-ERZET .
ZABS_EMP_ROLE-AENAM =
ZABSV_EMP_ROLE-AENAM .
ZABS_EMP_ROLE-AEDAT =
ZABSV_EMP_ROLE-AEDAT .
ZABS_EMP_ROLE-AEZET =
ZABSV_EMP_ROLE-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZABS_EMP_ROLE ##WARN_OK.
    ELSE.
    INSERT ZABS_EMP_ROLE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_EMP_ROLE-UPD_FLAG,
STATUS_ZABSV_EMP_ROLE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_EMP_ROLE.
  SELECT SINGLE * FROM ZABS_EMP_ROLE WHERE
PERNR = ZABSV_EMP_ROLE-PERNR .
ZABSV_EMP_ROLE-MANDT =
ZABS_EMP_ROLE-MANDT .
ZABSV_EMP_ROLE-PERNR =
ZABS_EMP_ROLE-PERNR .
ZABSV_EMP_ROLE-UROLE =
ZABS_EMP_ROLE-UROLE .
ZABSV_EMP_ROLE-PEVT =
ZABS_EMP_ROLE-PEVT .
ZABSV_EMP_ROLE-FPCNF =
ZABS_EMP_ROLE-FPCNF .
ZABSV_EMP_ROLE-ERNAM =
ZABS_EMP_ROLE-ERNAM .
ZABSV_EMP_ROLE-ERDAT =
ZABS_EMP_ROLE-ERDAT .
ZABSV_EMP_ROLE-ERZET =
ZABS_EMP_ROLE-ERZET .
ZABSV_EMP_ROLE-AENAM =
ZABS_EMP_ROLE-AENAM .
ZABSV_EMP_ROLE-AEDAT =
ZABS_EMP_ROLE-AEDAT .
ZABSV_EMP_ROLE-AEZET =
ZABS_EMP_ROLE-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_EMP_ROLE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_EMP_ROLE-PERNR TO
ZABS_EMP_ROLE-PERNR .
MOVE ZABSV_EMP_ROLE-MANDT TO
ZABS_EMP_ROLE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_EMP_ROLE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_EMP_ROLE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_EMP_ROLE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
