*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 23.04.2020 at 14:07:52
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABS_VQACHAR_GRP................................*
FORM GET_DATA_ZABS_VQACHAR_GRP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_QACHAR_GRP WHERE
(VIM_WHERETAB) .
    CLEAR ZABS_VQACHAR_GRP .
ZABS_VQACHAR_GRP-MANDT =
ZABS_QACHAR_GRP-MANDT .
ZABS_VQACHAR_GRP-INSPGROUP =
ZABS_QACHAR_GRP-INSPGROUP .
ZABS_VQACHAR_GRP-MSTR_CHAR =
ZABS_QACHAR_GRP-MSTR_CHAR .
ZABS_VQACHAR_GRP-GRP_SEQ =
ZABS_QACHAR_GRP-GRP_SEQ .
ZABS_VQACHAR_GRP-MSTR_DESC =
ZABS_QACHAR_GRP-MSTR_DESC .
<VIM_TOTAL_STRUC> = ZABS_VQACHAR_GRP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABS_VQACHAR_GRP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABS_VQACHAR_GRP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABS_VQACHAR_GRP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_QACHAR_GRP WHERE
  INSPGROUP = ZABS_VQACHAR_GRP-INSPGROUP AND
  MSTR_CHAR = ZABS_VQACHAR_GRP-MSTR_CHAR .
    IF SY-SUBRC = 0.
    DELETE ZABS_QACHAR_GRP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_QACHAR_GRP WHERE
  INSPGROUP = ZABS_VQACHAR_GRP-INSPGROUP AND
  MSTR_CHAR = ZABS_VQACHAR_GRP-MSTR_CHAR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_QACHAR_GRP.
    ENDIF.
ZABS_QACHAR_GRP-MANDT =
ZABS_VQACHAR_GRP-MANDT .
ZABS_QACHAR_GRP-INSPGROUP =
ZABS_VQACHAR_GRP-INSPGROUP .
ZABS_QACHAR_GRP-MSTR_CHAR =
ZABS_VQACHAR_GRP-MSTR_CHAR .
ZABS_QACHAR_GRP-GRP_SEQ =
ZABS_VQACHAR_GRP-GRP_SEQ .
ZABS_QACHAR_GRP-MSTR_DESC =
ZABS_VQACHAR_GRP-MSTR_DESC .
    IF SY-SUBRC = 0.
    UPDATE ZABS_QACHAR_GRP ##WARN_OK.
    ELSE.
    INSERT ZABS_QACHAR_GRP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABS_VQACHAR_GRP-UPD_FLAG,
STATUS_ZABS_VQACHAR_GRP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABS_VQACHAR_GRP.
  SELECT SINGLE * FROM ZABS_QACHAR_GRP WHERE
INSPGROUP = ZABS_VQACHAR_GRP-INSPGROUP AND
MSTR_CHAR = ZABS_VQACHAR_GRP-MSTR_CHAR .
ZABS_VQACHAR_GRP-MANDT =
ZABS_QACHAR_GRP-MANDT .
ZABS_VQACHAR_GRP-INSPGROUP =
ZABS_QACHAR_GRP-INSPGROUP .
ZABS_VQACHAR_GRP-MSTR_CHAR =
ZABS_QACHAR_GRP-MSTR_CHAR .
ZABS_VQACHAR_GRP-GRP_SEQ =
ZABS_QACHAR_GRP-GRP_SEQ .
ZABS_VQACHAR_GRP-MSTR_DESC =
ZABS_QACHAR_GRP-MSTR_DESC .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABS_VQACHAR_GRP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABS_VQACHAR_GRP-INSPGROUP TO
ZABS_QACHAR_GRP-INSPGROUP .
MOVE ZABS_VQACHAR_GRP-MSTR_CHAR TO
ZABS_QACHAR_GRP-MSTR_CHAR .
MOVE ZABS_VQACHAR_GRP-MANDT TO
ZABS_QACHAR_GRP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_QACHAR_GRP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_QACHAR_GRP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_QACHAR_GRP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
