*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 25.09.2020 at 01:44:42
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_AC_BGGRP..................................*
FORM GET_DATA_ZABSV_AC_BGGRP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_AC_BGGRP WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_AC_BGGRP .
ZABSV_AC_BGGRP-MANDT =
ZABS_AC_BGGRP-MANDT .
ZABSV_AC_BGGRP-MACKEY =
ZABS_AC_BGGRP-MACKEY .
ZABSV_AC_BGGRP-BAGGP =
ZABS_AC_BGGRP-BAGGP .
ZABSV_AC_BGGRP-ZZBAGCN =
ZABS_AC_BGGRP-ZZBAGCN .
ZABSV_AC_BGGRP-TOT_BOXES =
ZABS_AC_BGGRP-TOT_BOXES .
ZABSV_AC_BGGRP-AVG_CXN =
ZABS_AC_BGGRP-AVG_CXN .
ZABSV_AC_BGGRP-IBAG_NO =
ZABS_AC_BGGRP-IBAG_NO .
ZABSV_AC_BGGRP-FBAG_NO =
ZABS_AC_BGGRP-FBAG_NO .
ZABSV_AC_BGGRP-LDCDE =
ZABS_AC_BGGRP-LDCDE .
ZABSV_AC_BGGRP-LOADED =
ZABS_AC_BGGRP-LOADED .
ZABSV_AC_BGGRP-ERSDA =
ZABS_AC_BGGRP-ERSDA .
ZABSV_AC_BGGRP-ERTME =
ZABS_AC_BGGRP-ERTME .
ZABSV_AC_BGGRP-TMATNR =
ZABS_AC_BGGRP-TMATNR .
ZABSV_AC_BGGRP-AUFNR =
ZABS_AC_BGGRP-AUFNR .
ZABSV_AC_BGGRP-ZZTURMA =
ZABS_AC_BGGRP-ZZTURMA .
ZABSV_AC_BGGRP-TPLNR =
ZABS_AC_BGGRP-TPLNR .
ZABSV_AC_BGGRP-WERKS =
ZABS_AC_BGGRP-WERKS .
ZABSV_AC_BGGRP-LIDER_TURMA =
ZABS_AC_BGGRP-LIDER_TURMA .
ZABSV_AC_BGGRP-BTCRT =
ZABS_AC_BGGRP-BTCRT .
ZABSV_AC_BGGRP-MAKTX =
ZABS_AC_BGGRP-MAKTX .
ZABSV_AC_BGGRP-YMATNR =
ZABS_AC_BGGRP-YMATNR .
ZABSV_AC_BGGRP-CARIMBO =
ZABS_AC_BGGRP-CARIMBO .
ZABSV_AC_BGGRP-TOCLHTT =
ZABS_AC_BGGRP-TOCLHTT .
ZABSV_AC_BGGRP-CRIMEI =
ZABS_AC_BGGRP-CRIMEI .
ZABSV_AC_BGGRP-CRBADGE =
ZABS_AC_BGGRP-CRBADGE .
ZABSV_AC_BGGRP-CHIMEI =
ZABS_AC_BGGRP-CHIMEI .
ZABSV_AC_BGGRP-CHBADGE =
ZABS_AC_BGGRP-CHBADGE .
ZABSV_AC_BGGRP-STATUS =
ZABS_AC_BGGRP-STATUS .
ZABSV_AC_BGGRP-RDATE =
ZABS_AC_BGGRP-RDATE .
ZABSV_AC_BGGRP-ERNAM =
ZABS_AC_BGGRP-ERNAM .
ZABSV_AC_BGGRP-ERDAT =
ZABS_AC_BGGRP-ERDAT .
ZABSV_AC_BGGRP-ERZET =
ZABS_AC_BGGRP-ERZET .
ZABSV_AC_BGGRP-AENAM =
ZABS_AC_BGGRP-AENAM .
ZABSV_AC_BGGRP-AEDAT =
ZABS_AC_BGGRP-AEDAT .
ZABSV_AC_BGGRP-AEZET =
ZABS_AC_BGGRP-AEZET .
<VIM_TOTAL_STRUC> = ZABSV_AC_BGGRP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_AC_BGGRP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_AC_BGGRP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_AC_BGGRP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_AC_BGGRP WHERE
  MACKEY = ZABSV_AC_BGGRP-MACKEY AND
  BAGGP = ZABSV_AC_BGGRP-BAGGP .
    IF SY-SUBRC = 0.
    DELETE ZABS_AC_BGGRP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_AC_BGGRP WHERE
  MACKEY = ZABSV_AC_BGGRP-MACKEY AND
  BAGGP = ZABSV_AC_BGGRP-BAGGP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_AC_BGGRP.
    ENDIF.
ZABS_AC_BGGRP-MANDT =
ZABSV_AC_BGGRP-MANDT .
ZABS_AC_BGGRP-MACKEY =
ZABSV_AC_BGGRP-MACKEY .
ZABS_AC_BGGRP-BAGGP =
ZABSV_AC_BGGRP-BAGGP .
ZABS_AC_BGGRP-ZZBAGCN =
ZABSV_AC_BGGRP-ZZBAGCN .
ZABS_AC_BGGRP-TOT_BOXES =
ZABSV_AC_BGGRP-TOT_BOXES .
ZABS_AC_BGGRP-AVG_CXN =
ZABSV_AC_BGGRP-AVG_CXN .
ZABS_AC_BGGRP-IBAG_NO =
ZABSV_AC_BGGRP-IBAG_NO .
ZABS_AC_BGGRP-FBAG_NO =
ZABSV_AC_BGGRP-FBAG_NO .
ZABS_AC_BGGRP-LDCDE =
ZABSV_AC_BGGRP-LDCDE .
ZABS_AC_BGGRP-LOADED =
ZABSV_AC_BGGRP-LOADED .
ZABS_AC_BGGRP-ERSDA =
ZABSV_AC_BGGRP-ERSDA .
ZABS_AC_BGGRP-ERTME =
ZABSV_AC_BGGRP-ERTME .
ZABS_AC_BGGRP-TMATNR =
ZABSV_AC_BGGRP-TMATNR .
ZABS_AC_BGGRP-AUFNR =
ZABSV_AC_BGGRP-AUFNR .
ZABS_AC_BGGRP-ZZTURMA =
ZABSV_AC_BGGRP-ZZTURMA .
ZABS_AC_BGGRP-TPLNR =
ZABSV_AC_BGGRP-TPLNR .
ZABS_AC_BGGRP-WERKS =
ZABSV_AC_BGGRP-WERKS .
ZABS_AC_BGGRP-LIDER_TURMA =
ZABSV_AC_BGGRP-LIDER_TURMA .
ZABS_AC_BGGRP-BTCRT =
ZABSV_AC_BGGRP-BTCRT .
ZABS_AC_BGGRP-MAKTX =
ZABSV_AC_BGGRP-MAKTX .
ZABS_AC_BGGRP-YMATNR =
ZABSV_AC_BGGRP-YMATNR .
ZABS_AC_BGGRP-CARIMBO =
ZABSV_AC_BGGRP-CARIMBO .
ZABS_AC_BGGRP-TOCLHTT =
ZABSV_AC_BGGRP-TOCLHTT .
ZABS_AC_BGGRP-CRIMEI =
ZABSV_AC_BGGRP-CRIMEI .
ZABS_AC_BGGRP-CRBADGE =
ZABSV_AC_BGGRP-CRBADGE .
ZABS_AC_BGGRP-CHIMEI =
ZABSV_AC_BGGRP-CHIMEI .
ZABS_AC_BGGRP-CHBADGE =
ZABSV_AC_BGGRP-CHBADGE .
ZABS_AC_BGGRP-STATUS =
ZABSV_AC_BGGRP-STATUS .
ZABS_AC_BGGRP-RDATE =
ZABSV_AC_BGGRP-RDATE .
ZABS_AC_BGGRP-ERNAM =
ZABSV_AC_BGGRP-ERNAM .
ZABS_AC_BGGRP-ERDAT =
ZABSV_AC_BGGRP-ERDAT .
ZABS_AC_BGGRP-ERZET =
ZABSV_AC_BGGRP-ERZET .
ZABS_AC_BGGRP-AENAM =
ZABSV_AC_BGGRP-AENAM .
ZABS_AC_BGGRP-AEDAT =
ZABSV_AC_BGGRP-AEDAT .
ZABS_AC_BGGRP-AEZET =
ZABSV_AC_BGGRP-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZABS_AC_BGGRP ##WARN_OK.
    ELSE.
    INSERT ZABS_AC_BGGRP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_AC_BGGRP-UPD_FLAG,
STATUS_ZABSV_AC_BGGRP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_AC_BGGRP.
  SELECT SINGLE * FROM ZABS_AC_BGGRP WHERE
MACKEY = ZABSV_AC_BGGRP-MACKEY AND
BAGGP = ZABSV_AC_BGGRP-BAGGP .
ZABSV_AC_BGGRP-MANDT =
ZABS_AC_BGGRP-MANDT .
ZABSV_AC_BGGRP-MACKEY =
ZABS_AC_BGGRP-MACKEY .
ZABSV_AC_BGGRP-BAGGP =
ZABS_AC_BGGRP-BAGGP .
ZABSV_AC_BGGRP-ZZBAGCN =
ZABS_AC_BGGRP-ZZBAGCN .
ZABSV_AC_BGGRP-TOT_BOXES =
ZABS_AC_BGGRP-TOT_BOXES .
ZABSV_AC_BGGRP-AVG_CXN =
ZABS_AC_BGGRP-AVG_CXN .
ZABSV_AC_BGGRP-IBAG_NO =
ZABS_AC_BGGRP-IBAG_NO .
ZABSV_AC_BGGRP-FBAG_NO =
ZABS_AC_BGGRP-FBAG_NO .
ZABSV_AC_BGGRP-LDCDE =
ZABS_AC_BGGRP-LDCDE .
ZABSV_AC_BGGRP-LOADED =
ZABS_AC_BGGRP-LOADED .
ZABSV_AC_BGGRP-ERSDA =
ZABS_AC_BGGRP-ERSDA .
ZABSV_AC_BGGRP-ERTME =
ZABS_AC_BGGRP-ERTME .
ZABSV_AC_BGGRP-TMATNR =
ZABS_AC_BGGRP-TMATNR .
ZABSV_AC_BGGRP-AUFNR =
ZABS_AC_BGGRP-AUFNR .
ZABSV_AC_BGGRP-ZZTURMA =
ZABS_AC_BGGRP-ZZTURMA .
ZABSV_AC_BGGRP-TPLNR =
ZABS_AC_BGGRP-TPLNR .
ZABSV_AC_BGGRP-WERKS =
ZABS_AC_BGGRP-WERKS .
ZABSV_AC_BGGRP-LIDER_TURMA =
ZABS_AC_BGGRP-LIDER_TURMA .
ZABSV_AC_BGGRP-BTCRT =
ZABS_AC_BGGRP-BTCRT .
ZABSV_AC_BGGRP-MAKTX =
ZABS_AC_BGGRP-MAKTX .
ZABSV_AC_BGGRP-YMATNR =
ZABS_AC_BGGRP-YMATNR .
ZABSV_AC_BGGRP-CARIMBO =
ZABS_AC_BGGRP-CARIMBO .
ZABSV_AC_BGGRP-TOCLHTT =
ZABS_AC_BGGRP-TOCLHTT .
ZABSV_AC_BGGRP-CRIMEI =
ZABS_AC_BGGRP-CRIMEI .
ZABSV_AC_BGGRP-CRBADGE =
ZABS_AC_BGGRP-CRBADGE .
ZABSV_AC_BGGRP-CHIMEI =
ZABS_AC_BGGRP-CHIMEI .
ZABSV_AC_BGGRP-CHBADGE =
ZABS_AC_BGGRP-CHBADGE .
ZABSV_AC_BGGRP-STATUS =
ZABS_AC_BGGRP-STATUS .
ZABSV_AC_BGGRP-RDATE =
ZABS_AC_BGGRP-RDATE .
ZABSV_AC_BGGRP-ERNAM =
ZABS_AC_BGGRP-ERNAM .
ZABSV_AC_BGGRP-ERDAT =
ZABS_AC_BGGRP-ERDAT .
ZABSV_AC_BGGRP-ERZET =
ZABS_AC_BGGRP-ERZET .
ZABSV_AC_BGGRP-AENAM =
ZABS_AC_BGGRP-AENAM .
ZABSV_AC_BGGRP-AEDAT =
ZABS_AC_BGGRP-AEDAT .
ZABSV_AC_BGGRP-AEZET =
ZABS_AC_BGGRP-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_AC_BGGRP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_AC_BGGRP-MACKEY TO
ZABS_AC_BGGRP-MACKEY .
MOVE ZABSV_AC_BGGRP-BAGGP TO
ZABS_AC_BGGRP-BAGGP .
MOVE ZABSV_AC_BGGRP-MANDT TO
ZABS_AC_BGGRP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_AC_BGGRP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_AC_BGGRP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_AC_BGGRP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
