*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 16.07.2019 at 01:20:19
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_NRPLANNING................................*
FORM GET_DATA_ZABSV_NRPLANNING.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABST_NRPLANNING WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_NRPLANNING .
ZABSV_NRPLANNING-MANDT =
ZABST_NRPLANNING-MANDT .
ZABSV_NRPLANNING-NWERKS =
ZABST_NRPLANNING-NWERKS .
ZABSV_NRPLANNING-SEASON =
ZABST_NRPLANNING-SEASON .
ZABSV_NRPLANNING-GJAHR =
ZABST_NRPLANNING-GJAHR .
ZABSV_NRPLANNING-MATNR =
ZABST_NRPLANNING-MATNR .
ZABSV_NRPLANNING-MENGE =
ZABST_NRPLANNING-MENGE .
ZABSV_NRPLANNING-NPUOM =
ZABST_NRPLANNING-NPUOM .
ZABSV_NRPLANNING-RWERKS =
ZABST_NRPLANNING-RWERKS .
ZABSV_NRPLANNING-ERNAM =
ZABST_NRPLANNING-ERNAM .
ZABSV_NRPLANNING-ERDAT =
ZABST_NRPLANNING-ERDAT .
ZABSV_NRPLANNING-ERZET =
ZABST_NRPLANNING-ERZET .
ZABSV_NRPLANNING-AENAM =
ZABST_NRPLANNING-AENAM .
ZABSV_NRPLANNING-AEDAT =
ZABST_NRPLANNING-AEDAT .
ZABSV_NRPLANNING-AEZET =
ZABST_NRPLANNING-AEZET .
    SELECT SINGLE * FROM T001W WHERE
WERKS = ZABST_NRPLANNING-NWERKS .
    IF SY-SUBRC EQ 0.
ZABSV_NRPLANNING-NAME1 =
T001W-NAME1 .
ZABSV_NRPLANNING-NAME2 =
T001W-NAME2 .
    ENDIF.
    SELECT SINGLE * FROM MARA WHERE
MATNR = ZABST_NRPLANNING-MATNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM MAKT WHERE
MATNR = MARA-MATNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSV_NRPLANNING-MAKTX =
MAKT-MAKTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZABSV_NRPLANNING.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_NRPLANNING .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_NRPLANNING.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_NRPLANNING-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABST_NRPLANNING WHERE
  NWERKS = ZABSV_NRPLANNING-NWERKS AND
  SEASON = ZABSV_NRPLANNING-SEASON AND
  GJAHR = ZABSV_NRPLANNING-GJAHR AND
  MATNR = ZABSV_NRPLANNING-MATNR AND
  RWERKS = ZABSV_NRPLANNING-RWERKS .
    IF SY-SUBRC = 0.
    DELETE ZABST_NRPLANNING .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABST_NRPLANNING WHERE
  NWERKS = ZABSV_NRPLANNING-NWERKS AND
  SEASON = ZABSV_NRPLANNING-SEASON AND
  GJAHR = ZABSV_NRPLANNING-GJAHR AND
  MATNR = ZABSV_NRPLANNING-MATNR AND
  RWERKS = ZABSV_NRPLANNING-RWERKS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABST_NRPLANNING.
    ENDIF.
ZABST_NRPLANNING-MANDT =
ZABSV_NRPLANNING-MANDT .
ZABST_NRPLANNING-NWERKS =
ZABSV_NRPLANNING-NWERKS .
ZABST_NRPLANNING-SEASON =
ZABSV_NRPLANNING-SEASON .
ZABST_NRPLANNING-GJAHR =
ZABSV_NRPLANNING-GJAHR .
ZABST_NRPLANNING-MATNR =
ZABSV_NRPLANNING-MATNR .
ZABST_NRPLANNING-MENGE =
ZABSV_NRPLANNING-MENGE .
ZABST_NRPLANNING-NPUOM =
ZABSV_NRPLANNING-NPUOM .
ZABST_NRPLANNING-RWERKS =
ZABSV_NRPLANNING-RWERKS .
ZABST_NRPLANNING-ERNAM =
ZABSV_NRPLANNING-ERNAM .
ZABST_NRPLANNING-ERDAT =
ZABSV_NRPLANNING-ERDAT .
ZABST_NRPLANNING-ERZET =
ZABSV_NRPLANNING-ERZET .
ZABST_NRPLANNING-AENAM =
ZABSV_NRPLANNING-AENAM .
ZABST_NRPLANNING-AEDAT =
ZABSV_NRPLANNING-AEDAT .
ZABST_NRPLANNING-AEZET =
ZABSV_NRPLANNING-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZABST_NRPLANNING ##WARN_OK.
    ELSE.
    INSERT ZABST_NRPLANNING .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_NRPLANNING-UPD_FLAG,
STATUS_ZABSV_NRPLANNING-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_NRPLANNING.
  SELECT SINGLE * FROM ZABST_NRPLANNING WHERE
NWERKS = ZABSV_NRPLANNING-NWERKS AND
SEASON = ZABSV_NRPLANNING-SEASON AND
GJAHR = ZABSV_NRPLANNING-GJAHR AND
MATNR = ZABSV_NRPLANNING-MATNR AND
RWERKS = ZABSV_NRPLANNING-RWERKS .
ZABSV_NRPLANNING-MANDT =
ZABST_NRPLANNING-MANDT .
ZABSV_NRPLANNING-NWERKS =
ZABST_NRPLANNING-NWERKS .
ZABSV_NRPLANNING-SEASON =
ZABST_NRPLANNING-SEASON .
ZABSV_NRPLANNING-GJAHR =
ZABST_NRPLANNING-GJAHR .
ZABSV_NRPLANNING-MATNR =
ZABST_NRPLANNING-MATNR .
ZABSV_NRPLANNING-MENGE =
ZABST_NRPLANNING-MENGE .
ZABSV_NRPLANNING-NPUOM =
ZABST_NRPLANNING-NPUOM .
ZABSV_NRPLANNING-RWERKS =
ZABST_NRPLANNING-RWERKS .
ZABSV_NRPLANNING-ERNAM =
ZABST_NRPLANNING-ERNAM .
ZABSV_NRPLANNING-ERDAT =
ZABST_NRPLANNING-ERDAT .
ZABSV_NRPLANNING-ERZET =
ZABST_NRPLANNING-ERZET .
ZABSV_NRPLANNING-AENAM =
ZABST_NRPLANNING-AENAM .
ZABSV_NRPLANNING-AEDAT =
ZABST_NRPLANNING-AEDAT .
ZABSV_NRPLANNING-AEZET =
ZABST_NRPLANNING-AEZET .
    SELECT SINGLE * FROM T001W WHERE
WERKS = ZABST_NRPLANNING-NWERKS .
    IF SY-SUBRC EQ 0.
ZABSV_NRPLANNING-NAME1 =
T001W-NAME1 .
ZABSV_NRPLANNING-NAME2 =
T001W-NAME2 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSV_NRPLANNING-NAME1 .
      CLEAR ZABSV_NRPLANNING-NAME2 .
    ENDIF.
    SELECT SINGLE * FROM MARA WHERE
MATNR = ZABST_NRPLANNING-MATNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM MAKT WHERE
MATNR = MARA-MATNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSV_NRPLANNING-MAKTX =
MAKT-MAKTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZABSV_NRPLANNING-MAKTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSV_NRPLANNING-MAKTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_NRPLANNING USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_NRPLANNING-NWERKS TO
ZABST_NRPLANNING-NWERKS .
MOVE ZABSV_NRPLANNING-SEASON TO
ZABST_NRPLANNING-SEASON .
MOVE ZABSV_NRPLANNING-GJAHR TO
ZABST_NRPLANNING-GJAHR .
MOVE ZABSV_NRPLANNING-MATNR TO
ZABST_NRPLANNING-MATNR .
MOVE ZABSV_NRPLANNING-RWERKS TO
ZABST_NRPLANNING-RWERKS .
MOVE ZABSV_NRPLANNING-MANDT TO
ZABST_NRPLANNING-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABST_NRPLANNING'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABST_NRPLANNING TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABST_NRPLANNING'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZABSV_NRPLANNING USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZABST_NRPLANNING-MANDT =
ZABSV_NRPLANNING-MANDT .
ZABST_NRPLANNING-NWERKS =
ZABSV_NRPLANNING-NWERKS .
ZABST_NRPLANNING-SEASON =
ZABSV_NRPLANNING-SEASON .
ZABST_NRPLANNING-GJAHR =
ZABSV_NRPLANNING-GJAHR .
ZABST_NRPLANNING-MATNR =
ZABSV_NRPLANNING-MATNR .
ZABST_NRPLANNING-MENGE =
ZABSV_NRPLANNING-MENGE .
ZABST_NRPLANNING-NPUOM =
ZABSV_NRPLANNING-NPUOM .
ZABST_NRPLANNING-RWERKS =
ZABSV_NRPLANNING-RWERKS .
ZABST_NRPLANNING-ERNAM =
ZABSV_NRPLANNING-ERNAM .
ZABST_NRPLANNING-ERDAT =
ZABSV_NRPLANNING-ERDAT .
ZABST_NRPLANNING-ERZET =
ZABSV_NRPLANNING-ERZET .
ZABST_NRPLANNING-AENAM =
ZABSV_NRPLANNING-AENAM .
ZABST_NRPLANNING-AEDAT =
ZABSV_NRPLANNING-AEDAT .
ZABST_NRPLANNING-AEZET =
ZABSV_NRPLANNING-AEZET .
    SELECT SINGLE * FROM T001W WHERE
WERKS = ZABST_NRPLANNING-NWERKS .
    IF SY-SUBRC EQ 0.
ZABSV_NRPLANNING-NAME1 =
T001W-NAME1 .
ZABSV_NRPLANNING-NAME2 =
T001W-NAME2 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSV_NRPLANNING-NAME1 .
      CLEAR ZABSV_NRPLANNING-NAME2 .
    ENDIF.
    SELECT SINGLE * FROM MARA WHERE
MATNR = ZABST_NRPLANNING-MATNR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM MAKT WHERE
MATNR = MARA-MATNR AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZABSV_NRPLANNING-MAKTX =
MAKT-MAKTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZABSV_NRPLANNING-MAKTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZABSV_NRPLANNING-MAKTX .
    ENDIF.
ENDFORM.
