*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 01.12.2020 at 09:15:05
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_BGP_ACCOM.................................*
FORM GET_DATA_ZABSV_BGP_ACCOM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_BGP_ACCOM WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_BGP_ACCOM .
ZABSV_BGP_ACCOM-MANDT =
ZABS_BGP_ACCOM-MANDT .
ZABSV_BGP_ACCOM-ZZMACKEY =
ZABS_BGP_ACCOM-ZZMACKEY .
ZABSV_BGP_ACCOM-ZZKEYPOSNR =
ZABS_BGP_ACCOM-ZZKEYPOSNR .
ZABSV_BGP_ACCOM-FPOSNR =
ZABS_BGP_ACCOM-FPOSNR .
ZABSV_BGP_ACCOM-WERKS =
ZABS_BGP_ACCOM-WERKS .
ZABSV_BGP_ACCOM-DATUM =
ZABS_BGP_ACCOM-DATUM .
ZABSV_BGP_ACCOM-ZZTURMA =
ZABS_BGP_ACCOM-ZZTURMA .
ZABSV_BGP_ACCOM-ZZACTCG =
ZABS_BGP_ACCOM-ZZACTCG .
ZABSV_BGP_ACCOM-TPLNR =
ZABS_BGP_ACCOM-TPLNR .
ZABSV_BGP_ACCOM-TMATNR =
ZABS_BGP_ACCOM-TMATNR .
ZABSV_BGP_ACCOM-AUFNR =
ZABS_BGP_ACCOM-AUFNR .
ZABSV_BGP_ACCOM-IDRESOURCE =
ZABS_BGP_ACCOM-IDRESOURCE .
ZABSV_BGP_ACCOM-STRTDAT =
ZABS_BGP_ACCOM-STRTDAT .
ZABSV_BGP_ACCOM-STRTTIM =
ZABS_BGP_ACCOM-STRTTIM .
ZABSV_BGP_ACCOM-FINDAT =
ZABS_BGP_ACCOM-FINDAT .
ZABSV_BGP_ACCOM-FINTIM =
ZABS_BGP_ACCOM-FINTIM .
ZABSV_BGP_ACCOM-IDACTVL =
ZABS_BGP_ACCOM-IDACTVL .
ZABSV_BGP_ACCOM-MENGE =
ZABS_BGP_ACCOM-MENGE .
ZABSV_BGP_ACCOM-QMEIN =
ZABS_BGP_ACCOM-QMEIN .
ZABSV_BGP_ACCOM-ZZIMEI1 =
ZABS_BGP_ACCOM-ZZIMEI1 .
ZABSV_BGP_ACCOM-ZZAPPL =
ZABS_BGP_ACCOM-ZZAPPL .
ZABSV_BGP_ACCOM-ZZJUST =
ZABS_BGP_ACCOM-ZZJUST .
ZABSV_BGP_ACCOM-ZZBAGNO =
ZABS_BGP_ACCOM-ZZBAGNO .
ZABSV_BGP_ACCOM-ZZLONGITUDE =
ZABS_BGP_ACCOM-ZZLONGITUDE .
ZABSV_BGP_ACCOM-ZZLATITUDE =
ZABS_BGP_ACCOM-ZZLATITUDE .
ZABSV_BGP_ACCOM-ZZBAGGP =
ZABS_BGP_ACCOM-ZZBAGGP .
ZABSV_BGP_ACCOM-ZZCDATE =
ZABS_BGP_ACCOM-ZZCDATE .
ZABSV_BGP_ACCOM-ZZCTIME =
ZABS_BGP_ACCOM-ZZCTIME .
ZABSV_BGP_ACCOM-PERNR =
ZABS_BGP_ACCOM-PERNR .
ZABSV_BGP_ACCOM-IMEI =
ZABS_BGP_ACCOM-IMEI .
ZABSV_BGP_ACCOM-BADGE =
ZABS_BGP_ACCOM-BADGE .
ZABSV_BGP_ACCOM-ZZHDATE =
ZABS_BGP_ACCOM-ZZHDATE .
ZABSV_BGP_ACCOM-STATUS =
ZABS_BGP_ACCOM-STATUS .
ZABSV_BGP_ACCOM-MOBUSR =
ZABS_BGP_ACCOM-MOBUSR .
ZABSV_BGP_ACCOM-DUPLICATE =
ZABS_BGP_ACCOM-DUPLICATE .
ZABSV_BGP_ACCOM-RDATE =
ZABS_BGP_ACCOM-RDATE .
ZABSV_BGP_ACCOM-ERNAM =
ZABS_BGP_ACCOM-ERNAM .
ZABSV_BGP_ACCOM-ERDAT =
ZABS_BGP_ACCOM-ERDAT .
ZABSV_BGP_ACCOM-ERZET =
ZABS_BGP_ACCOM-ERZET .
ZABSV_BGP_ACCOM-AENAM =
ZABS_BGP_ACCOM-AENAM .
ZABSV_BGP_ACCOM-AEDAT =
ZABS_BGP_ACCOM-AEDAT .
ZABSV_BGP_ACCOM-AEZET =
ZABS_BGP_ACCOM-AEZET .
<VIM_TOTAL_STRUC> = ZABSV_BGP_ACCOM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_BGP_ACCOM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_BGP_ACCOM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_BGP_ACCOM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_BGP_ACCOM WHERE
  ZZMACKEY = ZABSV_BGP_ACCOM-ZZMACKEY AND
  ZZKEYPOSNR = ZABSV_BGP_ACCOM-ZZKEYPOSNR .
    IF SY-SUBRC = 0.
    DELETE ZABS_BGP_ACCOM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_BGP_ACCOM WHERE
  ZZMACKEY = ZABSV_BGP_ACCOM-ZZMACKEY AND
  ZZKEYPOSNR = ZABSV_BGP_ACCOM-ZZKEYPOSNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_BGP_ACCOM.
    ENDIF.
ZABS_BGP_ACCOM-MANDT =
ZABSV_BGP_ACCOM-MANDT .
ZABS_BGP_ACCOM-ZZMACKEY =
ZABSV_BGP_ACCOM-ZZMACKEY .
ZABS_BGP_ACCOM-ZZKEYPOSNR =
ZABSV_BGP_ACCOM-ZZKEYPOSNR .
ZABS_BGP_ACCOM-FPOSNR =
ZABSV_BGP_ACCOM-FPOSNR .
ZABS_BGP_ACCOM-WERKS =
ZABSV_BGP_ACCOM-WERKS .
ZABS_BGP_ACCOM-DATUM =
ZABSV_BGP_ACCOM-DATUM .
ZABS_BGP_ACCOM-ZZTURMA =
ZABSV_BGP_ACCOM-ZZTURMA .
ZABS_BGP_ACCOM-ZZACTCG =
ZABSV_BGP_ACCOM-ZZACTCG .
ZABS_BGP_ACCOM-TPLNR =
ZABSV_BGP_ACCOM-TPLNR .
ZABS_BGP_ACCOM-TMATNR =
ZABSV_BGP_ACCOM-TMATNR .
ZABS_BGP_ACCOM-AUFNR =
ZABSV_BGP_ACCOM-AUFNR .
ZABS_BGP_ACCOM-IDRESOURCE =
ZABSV_BGP_ACCOM-IDRESOURCE .
ZABS_BGP_ACCOM-STRTDAT =
ZABSV_BGP_ACCOM-STRTDAT .
ZABS_BGP_ACCOM-STRTTIM =
ZABSV_BGP_ACCOM-STRTTIM .
ZABS_BGP_ACCOM-FINDAT =
ZABSV_BGP_ACCOM-FINDAT .
ZABS_BGP_ACCOM-FINTIM =
ZABSV_BGP_ACCOM-FINTIM .
ZABS_BGP_ACCOM-IDACTVL =
ZABSV_BGP_ACCOM-IDACTVL .
ZABS_BGP_ACCOM-MENGE =
ZABSV_BGP_ACCOM-MENGE .
ZABS_BGP_ACCOM-QMEIN =
ZABSV_BGP_ACCOM-QMEIN .
ZABS_BGP_ACCOM-ZZIMEI1 =
ZABSV_BGP_ACCOM-ZZIMEI1 .
ZABS_BGP_ACCOM-ZZAPPL =
ZABSV_BGP_ACCOM-ZZAPPL .
ZABS_BGP_ACCOM-ZZJUST =
ZABSV_BGP_ACCOM-ZZJUST .
ZABS_BGP_ACCOM-ZZBAGNO =
ZABSV_BGP_ACCOM-ZZBAGNO .
ZABS_BGP_ACCOM-ZZLONGITUDE =
ZABSV_BGP_ACCOM-ZZLONGITUDE .
ZABS_BGP_ACCOM-ZZLATITUDE =
ZABSV_BGP_ACCOM-ZZLATITUDE .
ZABS_BGP_ACCOM-ZZBAGGP =
ZABSV_BGP_ACCOM-ZZBAGGP .
ZABS_BGP_ACCOM-ZZCDATE =
ZABSV_BGP_ACCOM-ZZCDATE .
ZABS_BGP_ACCOM-ZZCTIME =
ZABSV_BGP_ACCOM-ZZCTIME .
ZABS_BGP_ACCOM-PERNR =
ZABSV_BGP_ACCOM-PERNR .
ZABS_BGP_ACCOM-IMEI =
ZABSV_BGP_ACCOM-IMEI .
ZABS_BGP_ACCOM-BADGE =
ZABSV_BGP_ACCOM-BADGE .
ZABS_BGP_ACCOM-ZZHDATE =
ZABSV_BGP_ACCOM-ZZHDATE .
ZABS_BGP_ACCOM-STATUS =
ZABSV_BGP_ACCOM-STATUS .
ZABS_BGP_ACCOM-MOBUSR =
ZABSV_BGP_ACCOM-MOBUSR .
ZABS_BGP_ACCOM-DUPLICATE =
ZABSV_BGP_ACCOM-DUPLICATE .
ZABS_BGP_ACCOM-RDATE =
ZABSV_BGP_ACCOM-RDATE .
ZABS_BGP_ACCOM-ERNAM =
ZABSV_BGP_ACCOM-ERNAM .
ZABS_BGP_ACCOM-ERDAT =
ZABSV_BGP_ACCOM-ERDAT .
ZABS_BGP_ACCOM-ERZET =
ZABSV_BGP_ACCOM-ERZET .
ZABS_BGP_ACCOM-AENAM =
ZABSV_BGP_ACCOM-AENAM .
ZABS_BGP_ACCOM-AEDAT =
ZABSV_BGP_ACCOM-AEDAT .
ZABS_BGP_ACCOM-AEZET =
ZABSV_BGP_ACCOM-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZABS_BGP_ACCOM ##WARN_OK.
    ELSE.
    INSERT ZABS_BGP_ACCOM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_BGP_ACCOM-UPD_FLAG,
STATUS_ZABSV_BGP_ACCOM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_BGP_ACCOM.
  SELECT SINGLE * FROM ZABS_BGP_ACCOM WHERE
ZZMACKEY = ZABSV_BGP_ACCOM-ZZMACKEY AND
ZZKEYPOSNR = ZABSV_BGP_ACCOM-ZZKEYPOSNR .
ZABSV_BGP_ACCOM-MANDT =
ZABS_BGP_ACCOM-MANDT .
ZABSV_BGP_ACCOM-ZZMACKEY =
ZABS_BGP_ACCOM-ZZMACKEY .
ZABSV_BGP_ACCOM-ZZKEYPOSNR =
ZABS_BGP_ACCOM-ZZKEYPOSNR .
ZABSV_BGP_ACCOM-FPOSNR =
ZABS_BGP_ACCOM-FPOSNR .
ZABSV_BGP_ACCOM-WERKS =
ZABS_BGP_ACCOM-WERKS .
ZABSV_BGP_ACCOM-DATUM =
ZABS_BGP_ACCOM-DATUM .
ZABSV_BGP_ACCOM-ZZTURMA =
ZABS_BGP_ACCOM-ZZTURMA .
ZABSV_BGP_ACCOM-ZZACTCG =
ZABS_BGP_ACCOM-ZZACTCG .
ZABSV_BGP_ACCOM-TPLNR =
ZABS_BGP_ACCOM-TPLNR .
ZABSV_BGP_ACCOM-TMATNR =
ZABS_BGP_ACCOM-TMATNR .
ZABSV_BGP_ACCOM-AUFNR =
ZABS_BGP_ACCOM-AUFNR .
ZABSV_BGP_ACCOM-IDRESOURCE =
ZABS_BGP_ACCOM-IDRESOURCE .
ZABSV_BGP_ACCOM-STRTDAT =
ZABS_BGP_ACCOM-STRTDAT .
ZABSV_BGP_ACCOM-STRTTIM =
ZABS_BGP_ACCOM-STRTTIM .
ZABSV_BGP_ACCOM-FINDAT =
ZABS_BGP_ACCOM-FINDAT .
ZABSV_BGP_ACCOM-FINTIM =
ZABS_BGP_ACCOM-FINTIM .
ZABSV_BGP_ACCOM-IDACTVL =
ZABS_BGP_ACCOM-IDACTVL .
ZABSV_BGP_ACCOM-MENGE =
ZABS_BGP_ACCOM-MENGE .
ZABSV_BGP_ACCOM-QMEIN =
ZABS_BGP_ACCOM-QMEIN .
ZABSV_BGP_ACCOM-ZZIMEI1 =
ZABS_BGP_ACCOM-ZZIMEI1 .
ZABSV_BGP_ACCOM-ZZAPPL =
ZABS_BGP_ACCOM-ZZAPPL .
ZABSV_BGP_ACCOM-ZZJUST =
ZABS_BGP_ACCOM-ZZJUST .
ZABSV_BGP_ACCOM-ZZBAGNO =
ZABS_BGP_ACCOM-ZZBAGNO .
ZABSV_BGP_ACCOM-ZZLONGITUDE =
ZABS_BGP_ACCOM-ZZLONGITUDE .
ZABSV_BGP_ACCOM-ZZLATITUDE =
ZABS_BGP_ACCOM-ZZLATITUDE .
ZABSV_BGP_ACCOM-ZZBAGGP =
ZABS_BGP_ACCOM-ZZBAGGP .
ZABSV_BGP_ACCOM-ZZCDATE =
ZABS_BGP_ACCOM-ZZCDATE .
ZABSV_BGP_ACCOM-ZZCTIME =
ZABS_BGP_ACCOM-ZZCTIME .
ZABSV_BGP_ACCOM-PERNR =
ZABS_BGP_ACCOM-PERNR .
ZABSV_BGP_ACCOM-IMEI =
ZABS_BGP_ACCOM-IMEI .
ZABSV_BGP_ACCOM-BADGE =
ZABS_BGP_ACCOM-BADGE .
ZABSV_BGP_ACCOM-ZZHDATE =
ZABS_BGP_ACCOM-ZZHDATE .
ZABSV_BGP_ACCOM-STATUS =
ZABS_BGP_ACCOM-STATUS .
ZABSV_BGP_ACCOM-MOBUSR =
ZABS_BGP_ACCOM-MOBUSR .
ZABSV_BGP_ACCOM-DUPLICATE =
ZABS_BGP_ACCOM-DUPLICATE .
ZABSV_BGP_ACCOM-RDATE =
ZABS_BGP_ACCOM-RDATE .
ZABSV_BGP_ACCOM-ERNAM =
ZABS_BGP_ACCOM-ERNAM .
ZABSV_BGP_ACCOM-ERDAT =
ZABS_BGP_ACCOM-ERDAT .
ZABSV_BGP_ACCOM-ERZET =
ZABS_BGP_ACCOM-ERZET .
ZABSV_BGP_ACCOM-AENAM =
ZABS_BGP_ACCOM-AENAM .
ZABSV_BGP_ACCOM-AEDAT =
ZABS_BGP_ACCOM-AEDAT .
ZABSV_BGP_ACCOM-AEZET =
ZABS_BGP_ACCOM-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_BGP_ACCOM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_BGP_ACCOM-ZZMACKEY TO
ZABS_BGP_ACCOM-ZZMACKEY .
MOVE ZABSV_BGP_ACCOM-ZZKEYPOSNR TO
ZABS_BGP_ACCOM-ZZKEYPOSNR .
MOVE ZABSV_BGP_ACCOM-MANDT TO
ZABS_BGP_ACCOM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_BGP_ACCOM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_BGP_ACCOM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_BGP_ACCOM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
