*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 26.05.2020 at 07:28:26
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABS_V_USRPERNR.................................*
FORM GET_DATA_ZABS_V_USRPERNR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_USRPERNR WHERE
(VIM_WHERETAB) .
    CLEAR ZABS_V_USRPERNR .
ZABS_V_USRPERNR-MANDT =
ZABS_USRPERNR-MANDT .
ZABS_V_USRPERNR-ROUTE =
ZABS_USRPERNR-ROUTE .
ZABS_V_USRPERNR-COUNTER =
ZABS_USRPERNR-COUNTER .
ZABS_V_USRPERNR-OWROL =
ZABS_USRPERNR-OWROL .
ZABS_V_USRPERNR-PERNR =
ZABS_USRPERNR-PERNR .
ZABS_V_USRPERNR-LIFNR =
ZABS_USRPERNR-LIFNR .
<VIM_TOTAL_STRUC> = ZABS_V_USRPERNR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABS_V_USRPERNR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABS_V_USRPERNR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABS_V_USRPERNR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_USRPERNR WHERE
  ROUTE = ZABS_V_USRPERNR-ROUTE AND
  COUNTER = ZABS_V_USRPERNR-COUNTER .
    IF SY-SUBRC = 0.
    DELETE ZABS_USRPERNR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_USRPERNR WHERE
  ROUTE = ZABS_V_USRPERNR-ROUTE AND
  COUNTER = ZABS_V_USRPERNR-COUNTER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_USRPERNR.
    ENDIF.
ZABS_USRPERNR-MANDT =
ZABS_V_USRPERNR-MANDT .
ZABS_USRPERNR-ROUTE =
ZABS_V_USRPERNR-ROUTE .
ZABS_USRPERNR-COUNTER =
ZABS_V_USRPERNR-COUNTER .
ZABS_USRPERNR-OWROL =
ZABS_V_USRPERNR-OWROL .
ZABS_USRPERNR-PERNR =
ZABS_V_USRPERNR-PERNR .
ZABS_USRPERNR-LIFNR =
ZABS_V_USRPERNR-LIFNR .
    IF SY-SUBRC = 0.
    UPDATE ZABS_USRPERNR ##WARN_OK.
    ELSE.
    INSERT ZABS_USRPERNR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABS_V_USRPERNR-UPD_FLAG,
STATUS_ZABS_V_USRPERNR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABS_V_USRPERNR.
  SELECT SINGLE * FROM ZABS_USRPERNR WHERE
ROUTE = ZABS_V_USRPERNR-ROUTE AND
COUNTER = ZABS_V_USRPERNR-COUNTER .
ZABS_V_USRPERNR-MANDT =
ZABS_USRPERNR-MANDT .
ZABS_V_USRPERNR-ROUTE =
ZABS_USRPERNR-ROUTE .
ZABS_V_USRPERNR-COUNTER =
ZABS_USRPERNR-COUNTER .
ZABS_V_USRPERNR-OWROL =
ZABS_USRPERNR-OWROL .
ZABS_V_USRPERNR-PERNR =
ZABS_USRPERNR-PERNR .
ZABS_V_USRPERNR-LIFNR =
ZABS_USRPERNR-LIFNR .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABS_V_USRPERNR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABS_V_USRPERNR-ROUTE TO
ZABS_USRPERNR-ROUTE .
MOVE ZABS_V_USRPERNR-COUNTER TO
ZABS_USRPERNR-COUNTER .
MOVE ZABS_V_USRPERNR-MANDT TO
ZABS_USRPERNR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_USRPERNR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_USRPERNR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_USRPERNR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
