*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 07.05.2020 at 13:12:16
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABS_V_TASK_BAGS................................*
FORM GET_DATA_ZABS_V_TASK_BAGS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_TASK_BAGS WHERE
(VIM_WHERETAB) .
    CLEAR ZABS_V_TASK_BAGS .
ZABS_V_TASK_BAGS-MANDT =
ZABS_TASK_BAGS-MANDT .
ZABS_V_TASK_BAGS-TASK =
ZABS_TASK_BAGS-TASK .
ZABS_V_TASK_BAGS-BAGS_NUM =
ZABS_TASK_BAGS-BAGS_NUM .
ZABS_V_TASK_BAGS-MENGEH =
ZABS_TASK_BAGS-MENGEH .
<VIM_TOTAL_STRUC> = ZABS_V_TASK_BAGS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABS_V_TASK_BAGS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABS_V_TASK_BAGS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABS_V_TASK_BAGS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_TASK_BAGS WHERE
  TASK = ZABS_V_TASK_BAGS-TASK .
    IF SY-SUBRC = 0.
    DELETE ZABS_TASK_BAGS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_TASK_BAGS WHERE
  TASK = ZABS_V_TASK_BAGS-TASK .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_TASK_BAGS.
    ENDIF.
ZABS_TASK_BAGS-MANDT =
ZABS_V_TASK_BAGS-MANDT .
ZABS_TASK_BAGS-TASK =
ZABS_V_TASK_BAGS-TASK .
ZABS_TASK_BAGS-BAGS_NUM =
ZABS_V_TASK_BAGS-BAGS_NUM .
ZABS_TASK_BAGS-MENGEH =
ZABS_V_TASK_BAGS-MENGEH .
    IF SY-SUBRC = 0.
    UPDATE ZABS_TASK_BAGS ##WARN_OK.
    ELSE.
    INSERT ZABS_TASK_BAGS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABS_V_TASK_BAGS-UPD_FLAG,
STATUS_ZABS_V_TASK_BAGS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABS_V_TASK_BAGS.
  SELECT SINGLE * FROM ZABS_TASK_BAGS WHERE
TASK = ZABS_V_TASK_BAGS-TASK .
ZABS_V_TASK_BAGS-MANDT =
ZABS_TASK_BAGS-MANDT .
ZABS_V_TASK_BAGS-TASK =
ZABS_TASK_BAGS-TASK .
ZABS_V_TASK_BAGS-BAGS_NUM =
ZABS_TASK_BAGS-BAGS_NUM .
ZABS_V_TASK_BAGS-MENGEH =
ZABS_TASK_BAGS-MENGEH .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABS_V_TASK_BAGS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABS_V_TASK_BAGS-TASK TO
ZABS_TASK_BAGS-TASK .
MOVE ZABS_V_TASK_BAGS-MANDT TO
ZABS_TASK_BAGS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_TASK_BAGS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_TASK_BAGS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_TASK_BAGS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
