*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 11.05.2020 at 07:26:07
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_USR_EMP...................................*
FORM GET_DATA_ZABSV_USR_EMP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_USR_EMP WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_USR_EMP .
ZABSV_USR_EMP-MANDT =
ZABS_USR_EMP-MANDT .
ZABSV_USR_EMP-BNAME =
ZABS_USR_EMP-BNAME .
ZABSV_USR_EMP-UROLE =
ZABS_USR_EMP-UROLE .
ZABSV_USR_EMP-PERNR =
ZABS_USR_EMP-PERNR .
ZABSV_USR_EMP-LIFNR =
ZABS_USR_EMP-LIFNR .
ZABSV_USR_EMP-FARM =
ZABS_USR_EMP-FARM .
ZABSV_USR_EMP-PEVT =
ZABS_USR_EMP-PEVT .
ZABSV_USR_EMP-FPCNF =
ZABS_USR_EMP-FPCNF .
ZABSV_USR_EMP-FLEET =
ZABS_USR_EMP-FLEET .
ZABSV_USR_EMP-ERNAM =
ZABS_USR_EMP-ERNAM .
ZABSV_USR_EMP-ERDAT =
ZABS_USR_EMP-ERDAT .
ZABSV_USR_EMP-ERZET =
ZABS_USR_EMP-ERZET .
ZABSV_USR_EMP-AENAM =
ZABS_USR_EMP-AENAM .
ZABSV_USR_EMP-AEDAT =
ZABS_USR_EMP-AEDAT .
ZABSV_USR_EMP-AEZET =
ZABS_USR_EMP-AEZET .
<VIM_TOTAL_STRUC> = ZABSV_USR_EMP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_USR_EMP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_USR_EMP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_USR_EMP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_USR_EMP WHERE
  BNAME = ZABSV_USR_EMP-BNAME .
    IF SY-SUBRC = 0.
    DELETE ZABS_USR_EMP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_USR_EMP WHERE
  BNAME = ZABSV_USR_EMP-BNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_USR_EMP.
    ENDIF.
ZABS_USR_EMP-MANDT =
ZABSV_USR_EMP-MANDT .
ZABS_USR_EMP-BNAME =
ZABSV_USR_EMP-BNAME .
ZABS_USR_EMP-UROLE =
ZABSV_USR_EMP-UROLE .
ZABS_USR_EMP-PERNR =
ZABSV_USR_EMP-PERNR .
ZABS_USR_EMP-LIFNR =
ZABSV_USR_EMP-LIFNR .
ZABS_USR_EMP-FARM =
ZABSV_USR_EMP-FARM .
ZABS_USR_EMP-PEVT =
ZABSV_USR_EMP-PEVT .
ZABS_USR_EMP-FPCNF =
ZABSV_USR_EMP-FPCNF .
ZABS_USR_EMP-FLEET =
ZABSV_USR_EMP-FLEET .
ZABS_USR_EMP-ERNAM =
ZABSV_USR_EMP-ERNAM .
ZABS_USR_EMP-ERDAT =
ZABSV_USR_EMP-ERDAT .
ZABS_USR_EMP-ERZET =
ZABSV_USR_EMP-ERZET .
ZABS_USR_EMP-AENAM =
ZABSV_USR_EMP-AENAM .
ZABS_USR_EMP-AEDAT =
ZABSV_USR_EMP-AEDAT .
ZABS_USR_EMP-AEZET =
ZABSV_USR_EMP-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZABS_USR_EMP ##WARN_OK.
    ELSE.
    INSERT ZABS_USR_EMP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_USR_EMP-UPD_FLAG,
STATUS_ZABSV_USR_EMP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_USR_EMP.
  SELECT SINGLE * FROM ZABS_USR_EMP WHERE
BNAME = ZABSV_USR_EMP-BNAME .
ZABSV_USR_EMP-MANDT =
ZABS_USR_EMP-MANDT .
ZABSV_USR_EMP-BNAME =
ZABS_USR_EMP-BNAME .
ZABSV_USR_EMP-UROLE =
ZABS_USR_EMP-UROLE .
ZABSV_USR_EMP-PERNR =
ZABS_USR_EMP-PERNR .
ZABSV_USR_EMP-LIFNR =
ZABS_USR_EMP-LIFNR .
ZABSV_USR_EMP-FARM =
ZABS_USR_EMP-FARM .
ZABSV_USR_EMP-PEVT =
ZABS_USR_EMP-PEVT .
ZABSV_USR_EMP-FPCNF =
ZABS_USR_EMP-FPCNF .
ZABSV_USR_EMP-FLEET =
ZABS_USR_EMP-FLEET .
ZABSV_USR_EMP-ERNAM =
ZABS_USR_EMP-ERNAM .
ZABSV_USR_EMP-ERDAT =
ZABS_USR_EMP-ERDAT .
ZABSV_USR_EMP-ERZET =
ZABS_USR_EMP-ERZET .
ZABSV_USR_EMP-AENAM =
ZABS_USR_EMP-AENAM .
ZABSV_USR_EMP-AEDAT =
ZABS_USR_EMP-AEDAT .
ZABSV_USR_EMP-AEZET =
ZABS_USR_EMP-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_USR_EMP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_USR_EMP-BNAME TO
ZABS_USR_EMP-BNAME .
MOVE ZABSV_USR_EMP-MANDT TO
ZABS_USR_EMP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_USR_EMP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_USR_EMP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_USR_EMP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
