*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 26.06.2019 at 07:47:22
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_VTCHDR....................................*
FORM GET_DATA_ZABSV_VTCHDR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABST_VTCHDR WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_VTCHDR .
ZABSV_VTCHDR-MANDT =
ZABST_VTCHDR-MANDT .
ZABSV_VTCHDR-OBJID =
ZABST_VTCHDR-OBJID .
ZABSV_VTCHDR-OBJTP =
ZABST_VTCHDR-OBJTP .
ZABSV_VTCHDR-COMNT =
ZABST_VTCHDR-COMNT .
ZABSV_VTCHDR-K1NAM =
ZABST_VTCHDR-K1NAM .
ZABSV_VTCHDR-K2NAM =
ZABST_VTCHDR-K2NAM .
ZABSV_VTCHDR-K3NAM =
ZABST_VTCHDR-K3NAM .
ZABSV_VTCHDR-K4NAM =
ZABST_VTCHDR-K4NAM .
ZABSV_VTCHDR-K5NAM =
ZABST_VTCHDR-K5NAM .
<VIM_TOTAL_STRUC> = ZABSV_VTCHDR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_VTCHDR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_VTCHDR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_VTCHDR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABST_VTCHDR WHERE
  OBJID = ZABSV_VTCHDR-OBJID .
    IF SY-SUBRC = 0.
    DELETE ZABST_VTCHDR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABST_VTCHDR WHERE
  OBJID = ZABSV_VTCHDR-OBJID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABST_VTCHDR.
    ENDIF.
ZABST_VTCHDR-MANDT =
ZABSV_VTCHDR-MANDT .
ZABST_VTCHDR-OBJID =
ZABSV_VTCHDR-OBJID .
ZABST_VTCHDR-OBJTP =
ZABSV_VTCHDR-OBJTP .
ZABST_VTCHDR-COMNT =
ZABSV_VTCHDR-COMNT .
ZABST_VTCHDR-K1NAM =
ZABSV_VTCHDR-K1NAM .
ZABST_VTCHDR-K2NAM =
ZABSV_VTCHDR-K2NAM .
ZABST_VTCHDR-K3NAM =
ZABSV_VTCHDR-K3NAM .
ZABST_VTCHDR-K4NAM =
ZABSV_VTCHDR-K4NAM .
ZABST_VTCHDR-K5NAM =
ZABSV_VTCHDR-K5NAM .
    IF SY-SUBRC = 0.
    UPDATE ZABST_VTCHDR ##WARN_OK.
    ELSE.
    INSERT ZABST_VTCHDR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_VTCHDR-UPD_FLAG,
STATUS_ZABSV_VTCHDR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_VTCHDR.
  SELECT SINGLE * FROM ZABST_VTCHDR WHERE
OBJID = ZABSV_VTCHDR-OBJID .
ZABSV_VTCHDR-MANDT =
ZABST_VTCHDR-MANDT .
ZABSV_VTCHDR-OBJID =
ZABST_VTCHDR-OBJID .
ZABSV_VTCHDR-OBJTP =
ZABST_VTCHDR-OBJTP .
ZABSV_VTCHDR-COMNT =
ZABST_VTCHDR-COMNT .
ZABSV_VTCHDR-K1NAM =
ZABST_VTCHDR-K1NAM .
ZABSV_VTCHDR-K2NAM =
ZABST_VTCHDR-K2NAM .
ZABSV_VTCHDR-K3NAM =
ZABST_VTCHDR-K3NAM .
ZABSV_VTCHDR-K4NAM =
ZABST_VTCHDR-K4NAM .
ZABSV_VTCHDR-K5NAM =
ZABST_VTCHDR-K5NAM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_VTCHDR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_VTCHDR-OBJID TO
ZABST_VTCHDR-OBJID .
MOVE ZABSV_VTCHDR-MANDT TO
ZABST_VTCHDR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABST_VTCHDR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABST_VTCHDR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABST_VTCHDR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
