*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 01.05.2020 at 10:23:36
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABS_VMDCHAR_GRP................................*
FORM GET_DATA_ZABS_VMDCHAR_GRP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_MDCHAR_GRP WHERE
(VIM_WHERETAB) .
    CLEAR ZABS_VMDCHAR_GRP .
ZABS_VMDCHAR_GRP-MANDT =
ZABS_MDCHAR_GRP-MANDT .
ZABS_VMDCHAR_GRP-UROLE =
ZABS_MDCHAR_GRP-UROLE .
ZABS_VMDCHAR_GRP-CLASS =
ZABS_MDCHAR_GRP-CLASS .
<VIM_TOTAL_STRUC> = ZABS_VMDCHAR_GRP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABS_VMDCHAR_GRP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABS_VMDCHAR_GRP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABS_VMDCHAR_GRP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_MDCHAR_GRP WHERE
  UROLE = ZABS_VMDCHAR_GRP-UROLE AND
  CLASS = ZABS_VMDCHAR_GRP-CLASS .
    IF SY-SUBRC = 0.
    DELETE ZABS_MDCHAR_GRP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_MDCHAR_GRP WHERE
  UROLE = ZABS_VMDCHAR_GRP-UROLE AND
  CLASS = ZABS_VMDCHAR_GRP-CLASS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_MDCHAR_GRP.
    ENDIF.
ZABS_MDCHAR_GRP-MANDT =
ZABS_VMDCHAR_GRP-MANDT .
ZABS_MDCHAR_GRP-UROLE =
ZABS_VMDCHAR_GRP-UROLE .
ZABS_MDCHAR_GRP-CLASS =
ZABS_VMDCHAR_GRP-CLASS .
    IF SY-SUBRC = 0.
    UPDATE ZABS_MDCHAR_GRP ##WARN_OK.
    ELSE.
    INSERT ZABS_MDCHAR_GRP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABS_VMDCHAR_GRP-UPD_FLAG,
STATUS_ZABS_VMDCHAR_GRP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABS_VMDCHAR_GRP.
  SELECT SINGLE * FROM ZABS_MDCHAR_GRP WHERE
UROLE = ZABS_VMDCHAR_GRP-UROLE AND
CLASS = ZABS_VMDCHAR_GRP-CLASS .
ZABS_VMDCHAR_GRP-MANDT =
ZABS_MDCHAR_GRP-MANDT .
ZABS_VMDCHAR_GRP-UROLE =
ZABS_MDCHAR_GRP-UROLE .
ZABS_VMDCHAR_GRP-CLASS =
ZABS_MDCHAR_GRP-CLASS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABS_VMDCHAR_GRP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABS_VMDCHAR_GRP-UROLE TO
ZABS_MDCHAR_GRP-UROLE .
MOVE ZABS_VMDCHAR_GRP-CLASS TO
ZABS_MDCHAR_GRP-CLASS .
MOVE ZABS_VMDCHAR_GRP-MANDT TO
ZABS_MDCHAR_GRP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_MDCHAR_GRP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_MDCHAR_GRP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_MDCHAR_GRP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
