*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 18.09.2020 at 09:57:52
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_ACBRP_ELOG................................*
FORM GET_DATA_ZABSV_ACBRP_ELOG.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_ACBGRP_ELOG WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_ACBRP_ELOG .
ZABSV_ACBRP_ELOG-MANDT =
ZABS_ACBGRP_ELOG-MANDT .
ZABSV_ACBRP_ELOG-MACKEY =
ZABS_ACBGRP_ELOG-MACKEY .
ZABSV_ACBRP_ELOG-BAGGP =
ZABS_ACBGRP_ELOG-BAGGP .
ZABSV_ACBRP_ELOG-MSGID =
ZABS_ACBGRP_ELOG-MSGID .
ZABSV_ACBRP_ELOG-MSGNO =
ZABS_ACBGRP_ELOG-MSGNO .
ZABSV_ACBRP_ELOG-MSGTYP =
ZABS_ACBGRP_ELOG-MSGTYP .
ZABSV_ACBRP_ELOG-MSGTXT =
ZABS_ACBGRP_ELOG-MSGTXT .
ZABSV_ACBRP_ELOG-ERNAM =
ZABS_ACBGRP_ELOG-ERNAM .
ZABSV_ACBRP_ELOG-ERDAT =
ZABS_ACBGRP_ELOG-ERDAT .
ZABSV_ACBRP_ELOG-ERZET =
ZABS_ACBGRP_ELOG-ERZET .
ZABSV_ACBRP_ELOG-AENAM =
ZABS_ACBGRP_ELOG-AENAM .
ZABSV_ACBRP_ELOG-AEDAT =
ZABS_ACBGRP_ELOG-AEDAT .
ZABSV_ACBRP_ELOG-AEZET =
ZABS_ACBGRP_ELOG-AEZET .
<VIM_TOTAL_STRUC> = ZABSV_ACBRP_ELOG.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_ACBRP_ELOG .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_ACBRP_ELOG.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_ACBRP_ELOG-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_ACBGRP_ELOG WHERE
  MACKEY = ZABSV_ACBRP_ELOG-MACKEY AND
  BAGGP = ZABSV_ACBRP_ELOG-BAGGP .
    IF SY-SUBRC = 0.
    DELETE ZABS_ACBGRP_ELOG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_ACBGRP_ELOG WHERE
  MACKEY = ZABSV_ACBRP_ELOG-MACKEY AND
  BAGGP = ZABSV_ACBRP_ELOG-BAGGP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_ACBGRP_ELOG.
    ENDIF.
ZABS_ACBGRP_ELOG-MANDT =
ZABSV_ACBRP_ELOG-MANDT .
ZABS_ACBGRP_ELOG-MACKEY =
ZABSV_ACBRP_ELOG-MACKEY .
ZABS_ACBGRP_ELOG-BAGGP =
ZABSV_ACBRP_ELOG-BAGGP .
ZABS_ACBGRP_ELOG-MSGID =
ZABSV_ACBRP_ELOG-MSGID .
ZABS_ACBGRP_ELOG-MSGNO =
ZABSV_ACBRP_ELOG-MSGNO .
ZABS_ACBGRP_ELOG-MSGTYP =
ZABSV_ACBRP_ELOG-MSGTYP .
ZABS_ACBGRP_ELOG-MSGTXT =
ZABSV_ACBRP_ELOG-MSGTXT .
ZABS_ACBGRP_ELOG-ERNAM =
ZABSV_ACBRP_ELOG-ERNAM .
ZABS_ACBGRP_ELOG-ERDAT =
ZABSV_ACBRP_ELOG-ERDAT .
ZABS_ACBGRP_ELOG-ERZET =
ZABSV_ACBRP_ELOG-ERZET .
ZABS_ACBGRP_ELOG-AENAM =
ZABSV_ACBRP_ELOG-AENAM .
ZABS_ACBGRP_ELOG-AEDAT =
ZABSV_ACBRP_ELOG-AEDAT .
ZABS_ACBGRP_ELOG-AEZET =
ZABSV_ACBRP_ELOG-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZABS_ACBGRP_ELOG ##WARN_OK.
    ELSE.
    INSERT ZABS_ACBGRP_ELOG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_ACBRP_ELOG-UPD_FLAG,
STATUS_ZABSV_ACBRP_ELOG-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_ACBRP_ELOG.
  SELECT SINGLE * FROM ZABS_ACBGRP_ELOG WHERE
MACKEY = ZABSV_ACBRP_ELOG-MACKEY AND
BAGGP = ZABSV_ACBRP_ELOG-BAGGP .
ZABSV_ACBRP_ELOG-MANDT =
ZABS_ACBGRP_ELOG-MANDT .
ZABSV_ACBRP_ELOG-MACKEY =
ZABS_ACBGRP_ELOG-MACKEY .
ZABSV_ACBRP_ELOG-BAGGP =
ZABS_ACBGRP_ELOG-BAGGP .
ZABSV_ACBRP_ELOG-MSGID =
ZABS_ACBGRP_ELOG-MSGID .
ZABSV_ACBRP_ELOG-MSGNO =
ZABS_ACBGRP_ELOG-MSGNO .
ZABSV_ACBRP_ELOG-MSGTYP =
ZABS_ACBGRP_ELOG-MSGTYP .
ZABSV_ACBRP_ELOG-MSGTXT =
ZABS_ACBGRP_ELOG-MSGTXT .
ZABSV_ACBRP_ELOG-ERNAM =
ZABS_ACBGRP_ELOG-ERNAM .
ZABSV_ACBRP_ELOG-ERDAT =
ZABS_ACBGRP_ELOG-ERDAT .
ZABSV_ACBRP_ELOG-ERZET =
ZABS_ACBGRP_ELOG-ERZET .
ZABSV_ACBRP_ELOG-AENAM =
ZABS_ACBGRP_ELOG-AENAM .
ZABSV_ACBRP_ELOG-AEDAT =
ZABS_ACBGRP_ELOG-AEDAT .
ZABSV_ACBRP_ELOG-AEZET =
ZABS_ACBGRP_ELOG-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_ACBRP_ELOG USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_ACBRP_ELOG-MACKEY TO
ZABS_ACBGRP_ELOG-MACKEY .
MOVE ZABSV_ACBRP_ELOG-BAGGP TO
ZABS_ACBGRP_ELOG-BAGGP .
MOVE ZABSV_ACBRP_ELOG-MANDT TO
ZABS_ACBGRP_ELOG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_ACBGRP_ELOG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_ACBGRP_ELOG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_ACBGRP_ELOG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
