*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 18.09.2020 at 07:07:08
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZABSV_HDR_ACCOM.................................*
FORM GET_DATA_ZABSV_HDR_ACCOM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZABS_HDR_ACCOM WHERE
(VIM_WHERETAB) .
    CLEAR ZABSV_HDR_ACCOM .
ZABSV_HDR_ACCOM-MANDT =
ZABS_HDR_ACCOM-MANDT .
ZABSV_HDR_ACCOM-PERNR =
ZABS_HDR_ACCOM-PERNR .
ZABSV_HDR_ACCOM-ZZMACKEY =
ZABS_HDR_ACCOM-ZZMACKEY .
ZABSV_HDR_ACCOM-STRTDAT =
ZABS_HDR_ACCOM-STRTDAT .
ZABSV_HDR_ACCOM-ACCOM =
ZABS_HDR_ACCOM-ACCOM .
ZABSV_HDR_ACCOM-LPOSNR =
ZABS_HDR_ACCOM-LPOSNR .
ZABSV_HDR_ACCOM-ERNAM =
ZABS_HDR_ACCOM-ERNAM .
ZABSV_HDR_ACCOM-ERDAT =
ZABS_HDR_ACCOM-ERDAT .
ZABSV_HDR_ACCOM-ERZET =
ZABS_HDR_ACCOM-ERZET .
ZABSV_HDR_ACCOM-AENAM =
ZABS_HDR_ACCOM-AENAM .
ZABSV_HDR_ACCOM-AEDAT =
ZABS_HDR_ACCOM-AEDAT .
ZABSV_HDR_ACCOM-AEZET =
ZABS_HDR_ACCOM-AEZET .
<VIM_TOTAL_STRUC> = ZABSV_HDR_ACCOM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZABSV_HDR_ACCOM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZABSV_HDR_ACCOM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZABSV_HDR_ACCOM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZABS_HDR_ACCOM WHERE
  PERNR = ZABSV_HDR_ACCOM-PERNR AND
  ZZMACKEY = ZABSV_HDR_ACCOM-ZZMACKEY .
    IF SY-SUBRC = 0.
    DELETE ZABS_HDR_ACCOM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZABS_HDR_ACCOM WHERE
  PERNR = ZABSV_HDR_ACCOM-PERNR AND
  ZZMACKEY = ZABSV_HDR_ACCOM-ZZMACKEY .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZABS_HDR_ACCOM.
    ENDIF.
ZABS_HDR_ACCOM-MANDT =
ZABSV_HDR_ACCOM-MANDT .
ZABS_HDR_ACCOM-PERNR =
ZABSV_HDR_ACCOM-PERNR .
ZABS_HDR_ACCOM-ZZMACKEY =
ZABSV_HDR_ACCOM-ZZMACKEY .
ZABS_HDR_ACCOM-STRTDAT =
ZABSV_HDR_ACCOM-STRTDAT .
ZABS_HDR_ACCOM-ACCOM =
ZABSV_HDR_ACCOM-ACCOM .
ZABS_HDR_ACCOM-LPOSNR =
ZABSV_HDR_ACCOM-LPOSNR .
ZABS_HDR_ACCOM-ERNAM =
ZABSV_HDR_ACCOM-ERNAM .
ZABS_HDR_ACCOM-ERDAT =
ZABSV_HDR_ACCOM-ERDAT .
ZABS_HDR_ACCOM-ERZET =
ZABSV_HDR_ACCOM-ERZET .
ZABS_HDR_ACCOM-AENAM =
ZABSV_HDR_ACCOM-AENAM .
ZABS_HDR_ACCOM-AEDAT =
ZABSV_HDR_ACCOM-AEDAT .
ZABS_HDR_ACCOM-AEZET =
ZABSV_HDR_ACCOM-AEZET .
    IF SY-SUBRC = 0.
    UPDATE ZABS_HDR_ACCOM ##WARN_OK.
    ELSE.
    INSERT ZABS_HDR_ACCOM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZABSV_HDR_ACCOM-UPD_FLAG,
STATUS_ZABSV_HDR_ACCOM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZABSV_HDR_ACCOM.
  SELECT SINGLE * FROM ZABS_HDR_ACCOM WHERE
PERNR = ZABSV_HDR_ACCOM-PERNR AND
ZZMACKEY = ZABSV_HDR_ACCOM-ZZMACKEY .
ZABSV_HDR_ACCOM-MANDT =
ZABS_HDR_ACCOM-MANDT .
ZABSV_HDR_ACCOM-PERNR =
ZABS_HDR_ACCOM-PERNR .
ZABSV_HDR_ACCOM-ZZMACKEY =
ZABS_HDR_ACCOM-ZZMACKEY .
ZABSV_HDR_ACCOM-STRTDAT =
ZABS_HDR_ACCOM-STRTDAT .
ZABSV_HDR_ACCOM-ACCOM =
ZABS_HDR_ACCOM-ACCOM .
ZABSV_HDR_ACCOM-LPOSNR =
ZABS_HDR_ACCOM-LPOSNR .
ZABSV_HDR_ACCOM-ERNAM =
ZABS_HDR_ACCOM-ERNAM .
ZABSV_HDR_ACCOM-ERDAT =
ZABS_HDR_ACCOM-ERDAT .
ZABSV_HDR_ACCOM-ERZET =
ZABS_HDR_ACCOM-ERZET .
ZABSV_HDR_ACCOM-AENAM =
ZABS_HDR_ACCOM-AENAM .
ZABSV_HDR_ACCOM-AEDAT =
ZABS_HDR_ACCOM-AEDAT .
ZABSV_HDR_ACCOM-AEZET =
ZABS_HDR_ACCOM-AEZET .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZABSV_HDR_ACCOM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZABSV_HDR_ACCOM-PERNR TO
ZABS_HDR_ACCOM-PERNR .
MOVE ZABSV_HDR_ACCOM-ZZMACKEY TO
ZABS_HDR_ACCOM-ZZMACKEY .
MOVE ZABSV_HDR_ACCOM-MANDT TO
ZABS_HDR_ACCOM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZABS_HDR_ACCOM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZABS_HDR_ACCOM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZABS_HDR_ACCOM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
