*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFMPLMTOP.                  " Global Data
  INCLUDE LZFMPLMUXX.                  " Function Modules
INCLUDE LZFMPLMCLS.
*INCLUDE LZFMACMCLS.
*INCLUDE /AGRI/LFMACMCLS.
*  INCLUDE /AGRI/LFMACMNCLS.

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /AGRI/LFMACMNF...                  " Subroutines
* INCLUDE /AGRI/LFMACMNO...                  " PBO-Modules
* INCLUDE /AGRI/LFMACMNI...                  " PAI-Modules
* INCLUDE /AGRI/LFMACMNE...                  " Events
* INCLUDE /AGRI/LFMACMNP...                  " Local class implement.

INCLUDE LZFMPLMO01.
*INCLUDE LZFMACMO01.
*INCLUDE /AGRI/LFMACMO01.
*INCLUDE /AGRI/LFMACMNO01.

INCLUDE LZFMPLMF0T.
*INCLUDE LZFMACMF0T.
*INCLUDE /AGRI/LFMACMF0T.
*INCLUDE /AGRI/LFMACMNF0T.

INCLUDE LZFMPLMF0S.
*INCLUDE LZFMACMF0S.
*INCLUDE /AGRI/LFMACMF0S.
*INCLUDE /AGRI/LFMACMNF0S.

INCLUDE LZFMPLMO0T.
*INCLUDE LZFMACMO0T.
*INCLUDE /AGRI/LFMACMO0T.
*INCLUDE /AGRI/LFMACMNO0T.

INCLUDE LZFMPLMF0C.
*INCLUDE LZFMACMF0C.
*INCLUDE /AGRI/LFMACMF0C.
*INCLUDE /AGRI/LFMACMNF0C.

INCLUDE LZFMPLMF0W.
*INCLUDE LZFMACMF0W.
*INCLUDE /AGRI/LFMACMF0W.
*INCLUDE /AGRI/LFMACMNF0W.

INCLUDE LZFMPLMF0F.
*INCLUDE LZFMACMF0F.
*INCLUDE /AGRI/LFMACMF0F.
*INCLUDE /AGRI/LFMACMNF0F.

INCLUDE LZFMPLMF0H.
*INCLUDE LZFMACMF0H.
*INCLUDE /AGRI/LFMACMF0H.
*INCLUDE /AGRI/LFMACMNF0H.

INCLUDE LZFMPLMI01.
*INCLUDE LZFMACMI01.
*INCLUDE /AGRI/LFMACMI01.
*INCLUDE /AGRI/LFMACMNI01.

INCLUDE LZFMPLMF0E.
*INCLUDE LZFMACMF0E.
*INCLUDE /AGRI/LFMACMF0E.
*INCLUDE /AGRI/LFMACMNF0E.

INCLUDE LZFMPLMF0D.
*INCLUDE LZFMACMF0D.
*INCLUDE /AGRI/LFMACMF0D.
*INCLUDE /AGRI/LFMACMNF0D.

INCLUDE LZFMPLMF0M.
*INCLUDE LZFMACMF0M.
*INCLUDE /AGRI/LFMACMF0M.
*INCLUDE /AGRI/LFMACMNF0M.

INCLUDE LZFMPLMF0A.
*INCLUDE LZFMACMF0A.
*INCLUDE /AGRI/LFMACMF0A.
*INCLUDE /AGRI/LFMACMNF0A.

INCLUDE LZFMPLMF0N.
*INCLUDE LZFMACMF0N.
*INCLUDE /AGRI/LFMACMF0N.
*INCLUDE /AGRI/LFMACMNF0N.

INCLUDE LZFMPLMF0I.
*INCLUDE LZFMACMF0I.
*INCLUDE /AGRI/LFMACMF0I.
*INCLUDE /AGRI/LFMACMNF0I.

INCLUDE LZFMPLMF0U.
*INCLUDE LZFMACMF0U.
*INCLUDE /AGRI/LFMACMF0U.
*INCLUDE /AGRI/LFMACMNF0U.

INCLUDE LZFMPLMF0G.
*INCLUDE LZFMACMF0G.
*INCLUDE /AGRI/LFMACMF0G.
*INCLUDE /AGRI/LFMACMNF0G.

INCLUDE LZFMPLMF0R.
*INCLUDE LZFMACMF0R.
*INCLUDE /AGRI/LFMACMF0R.
*INCLUDE /AGRI/LFMACMNF0R.

INCLUDE LZFMPLMF0O.
*INCLUDE LZFMACMF0O.
*INCLUDE /AGRI/LFMACMF0O.
*INCLUDE /AGRI/LFMACMNF0O.

INCLUDE LZFMPLMF0V.
*INCLUDE LZFMACMF0V.
*INCLUDE /AGRI/LFMACMF0V.
*INCLUDE /AGRI/LFMACMNF0V.

INCLUDE LZFMPLMF0L.
*INCLUDE LZFMACMF0L.
*INCLUDE /AGRI/LFMACMF0L.
*INCLUDE /AGRI/LFMACMNF0L.

INCLUDE LZFMPLMF0B.
*INCLUDE LZFMACMF0B.
*INCLUDE /AGRI/LFMACMF0B.
*INCLUDE /AGRI/LFMACMNF0B.
*{   INSERT         S4HK904172                                        1
*
INCLUDE LZFMPLMF0P.
*INCLUDE LZFMACMF0P.
*INCLUDE /agri/lFMACmf0p.
*}   INSERT
