*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFMRCATOP.                   " Global Data
  INCLUDE LZFMRCAUXX.                   " Function Modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /AGRI/LGLFLAF...                   " Subroutines
* INCLUDE /AGRI/LGLFLAO...                   " PBO-Modules
* INCLUDE /AGRI/LGLFLAI...                   " PAI-Modules
* INCLUDE /AGRI/LGLFLAE...                   " Events
* INCLUDE /AGRI/LGLFLAP...                   " Local class implement.

INCLUDE LZFMRCAF0A.
*INCLUDE LZFMARAF0A.
*INCLUDE LZFMACAF0A.
INCLUDE LZFMRCAF0B.
*INCLUDE LZFMARAF0B.
*INCLUDE LZFMACAF0B.
INCLUDE LZFMRCAF0C.
*INCLUDE LZFMARAF0C.
*INCLUDE LZFMACAF0C.
INCLUDE LZFMRCAF0F.
*INCLUDE LZFMARAF0F.
*INCLUDE LZFMACAF0F.
INCLUDE LZFMRCAF0G.
*INCLUDE LZFMARAF0G.
*INCLUDE LZFMACAF0G.
INCLUDE LZFMRCAF0H.
*INCLUDE LZFMARAF0H.
*INCLUDE LZFMACAF0H.
INCLUDE LZFMRCAF0I.
*INCLUDE LZFMARAF0I.
*INCLUDE LZFMACAF0I.
INCLUDE LZFMRCAF0J.
*INCLUDE LZFMARAF0J.
*INCLUDE LZFMACAF0J.
INCLUDE LZFMRCAF0K.
*INCLUDE LZFMARAF0K.
*INCLUDE LZFMACAF0K.
INCLUDE LZFMRCAF0L.
*INCLUDE LZFMARAF0L.
*INCLUDE LZFMACAF0L.
INCLUDE LZFMRCAF0M.
*INCLUDE LZFMARAF0M.
*INCLUDE LZFMACAF0M.
INCLUDE LZFMRCAF0N.
*INCLUDE LZFMARAF0N.
*INCLUDE LZFMACAF0N.
INCLUDE LZFMRCAF0O.
*INCLUDE LZFMARAF0O.
*INCLUDE LZFMACAF0O.
INCLUDE LZFMRCAF0P.
*INCLUDE LZFMARAF0P.
*INCLUDE LZFMACAF0P.
INCLUDE LZFMRCAF0Q.
*INCLUDE LZFMARAF0Q.
*INCLUDE LZFMACAF0Q.
INCLUDE LZFMRCAF0R.
*INCLUDE LZFMARAF0R.
*INCLUDE LZFMACAF0R.
INCLUDE LZFMRCAF0S.
*INCLUDE LZFMARAF0S.
*INCLUDE LZFMACAF0S.
INCLUDE LZFMRCAF0T.
*INCLUDE LZFMARAF0T.
*INCLUDE LZFMACAF0T.
INCLUDE LZFMRCAF0U.
*INCLUDE LZFMARAF0U.
*INCLUDE LZFMACAF0U.
INCLUDE LZFMRCAF0V.
*INCLUDE LZFMARAF0V.
*INCLUDE LZFMACAF0V.
INCLUDE LZFMRCAF0W.
*INCLUDE LZFMARAF0W.
*INCLUDE LZFMACAF0W.
